.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "VIGIL" "1" "May 2015" "" ""
.
.SH "NAME"
\fBvigil\fR \- turn URLs into BibTeX records
.
.SH "SYNOPSIS"
\fBvigil\fR [\-c] [\fIinput\-file\fR]
.
.SH "DESCRIPTION"
\fBvigil\fR will parse the URLs (on per line) in \fIinput\-file\fR (or if missing on \fIstdin\fR) and output the corresponding bibtex(1) records on stdout\.
.
.P
If the URL points to a known forum (Hacker News, Reddit), the BibTeX record will be the record for the article the discussion on the forum is about, with a link to the discussion in the \fBAnnote\fR field of the record\.
.
.SH "OPTIONS"
.
.TP
\fB\-c\fR
Copy the records to the clipboard\. This feature is useful when used in coordination whith programs like BibDesk on MacOSX, which allow import from the clipboard with a keystroke\.
.
.SH "SYNTAX"
.
.SH "ENVIRONMENT"
.
.SH "RETURN VALUES"
.
.SH "STANDARDS"
.
.SH "SECURITY CONSIDERATIONS"
.
.SH "BUGS"
.
.SH "HISTORY"
.
.SH "AUTHOR"
.
.SH "COPYRIGHT"
.
.SH "SEE ALSO"
.
.SH "TODO"

